"""Glyphes des rouleaux — pixel-art 16x16, source de vérité.

Chaque caractère est une clé de `artKeys` dans tokens.json ; « . » = transparent.
Univers : électronique/maker, rétro-computing & gaming, geek pop.
L'invader est le jackpot (le « 7 » de cette machine).

L'ordre de la liste est l'ordre de valeur croissante — il sert aussi
d'index de symbole dans lib/core (SYM_RESISTOR = 0, ...).
"""

SYMBOLS = [
    {
        "id": "RESISTOR", "label": "Résistance", "family": "Électronique / maker",
        "note": "Le symbole le plus faible. Seule teinte non néon de la palette (tan).",
        "art": [
            "................",
            "................",
            "................",
            "................",
            "...kkkkkkkkkk...",
            "...kbbbbbbbbk...",
            "...kbcbmbybbk...",
            "ssskbcbmbybbksss",
            "ssskbcbmbybbksss",
            "...kbcbmbybbk...",
            "...kbbbbbbbbk...",
            "...kkkkkkkkkk...",
            "................",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "LED", "label": "LED", "family": "Électronique / maker",
        "note": "Dôme rouge, éclat blanc en haut à gauche, pattes inégales.",
        "art": [
            "................",
            "......kkkk......",
            "....kkrrrrkk....",
            "...krrrrrrrrk...",
            "..krwrrrrrrrrk..",
            "..krwrrrrrrrrk..",
            "..krrrrrrrrrrk..",
            "..krrrrrrrrrrk..",
            "..kkkkkkkkkkkk..",
            "..kssssssssssk..",
            "..kkkkkkkkkkkk..",
            "......s..s......",
            "......s..s......",
            "......s..s......",
            ".........s......",
            "................",
        ],
    },
    {
        "id": "CHIP", "label": "Puce", "family": "Électronique / maker",
        "note": "Le cœur du Cardputer. Point magenta = repère broche 1.",
        "art": [
            "................",
            "................",
            "...kkkkkkkkkk...",
            "...kSmSSSSSSk...",
            "ssskSSccccSSksss",
            "...kSSccccSSk...",
            "ssskSSccccSSksss",
            "...kSSccccSSk...",
            "ssskSSccccSSksss",
            "...kSSccccSSk...",
            "ssskSSSSSSSSksss",
            "...kSSSSSSSSk...",
            "...kkkkkkkkkk...",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "FLOPPY", "label": "Disquette", "family": "Rétro-computing",
        "note": "Volet acier fendu en haut, grande étiquette cyan en bas.",
        "art": [
            "................",
            "................",
            "..kkkkkkkkkkkk..",
            "..kvvssssssvvk..",
            "..kvvsskkssvvk..",
            "..kvvsskkssvvk..",
            "..kvvssssssvvk..",
            "..kvvvvvvvvvvk..",
            "..kvccccccccvk..",
            "..kvcCCCCCCcvk..",
            "..kvccccccccvk..",
            "..kvcCCCCCCcvk..",
            "..kvccccccccvk..",
            "..kkkkkkkkkkkk..",
            "................",
            "................",
        ],
    },
    {
        "id": "GAMEPAD", "label": "Manette", "family": "Rétro-gaming",
        "note": "Croix directionnelle creusée, deux boutons néon en diagonale.",
        "art": [
            "................",
            "................",
            "................",
            "................",
            "................",
            ".kkkkkkkkkkkkkk.",
            ".kSSSSSSSSSSSSk.",
            ".kSSsSSSmmSSSSk.",
            ".kSsssSSmmSyySk.",
            ".kSSsSSSSSSyySk.",
            ".kSSSSSSSSSSSSk.",
            ".kkkkkkkkkkkkkk.",
            "................",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "CRT", "label": "Écran CRT", "family": "Rétro-computing",
        "note": "Phosphore vert avec lignes de balayage alternées.",
        "art": [
            "................",
            "................",
            ".kkkkkkkkkkkkkk.",
            ".kSSSSSSSSSSSSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSkggggggggkSk.",
            ".kSkGGGGGGGGkSk.",
            ".kSkggggggggkSk.",
            ".kSkGGGGGGGGkSk.",
            ".kSkkkkkkkkkkSk.",
            ".kSSSSSSSSSSSSk.",
            ".kkkkkkkkkkkkkk.",
            ".....kkkkkk.....",
            ".....kSSSSk.....",
            "..kkkkkkkkkkkk..",
            "..kSSSSSSSSSSk..",
        ],
    },
    {
        "id": "D20", "label": "Dé 20", "family": "Geek pop",
        "note": "Le hasard côté geek. Hexagone cyan, « 20 » en clair.",
        "art": [
            "................",
            "................",
            "......kkkk......",
            "....kkcccckk....",
            "..kkcccccccckk..",
            "..kcccccccccck..",
            "..kccwwwcwwwck..",
            "..kccccwcwcwck..",
            "..kccwwwcwcwck..",
            "..kccwcccwcwck..",
            "..kccwwwcwwwck..",
            "..kcccccccccck..",
            "..kkcccccccckk..",
            "....kkcccckk....",
            "......kkkk......",
            "................",
        ],
    },
    {
        "id": "INVADER", "label": "Invader", "family": "Geek pop — JACKPOT",
        "note": "Le « 7 » de cette machine. Sans contour : il doit briller, pas être cerné.",
        "art": [
            "................",
            "................",
            "................",
            "...g........g...",
            "....g......g....",
            "...gggggggggg...",
            "..ggg..gg..ggg..",
            ".gggggggggggggg.",
            ".g.gggggggggg.g.",
            ".g.g........g.g.",
            "....gg....gg....",
            "..gg........gg..",
            "................",
            "................",
            "................",
            "................",
        ],
    },
]

# Jeu de glyphes CLASSIQUES — la machine à sous traditionnelle, en
# correspondance rang par rang avec le jeu geek (même index, même gain).
# Sert au réglage « glyphes normaux » et à la page d'aide.
CLASSIC_SYMBOLS = [
    {
        "id": "CHERRY", "label": "Cerises", "maps": "RESISTOR",
        "art": [
            "................",
            "........gg......",
            ".......gg.......",
            "......gg........",
            ".....gg.g.......",
            ".....g...g......",
            "....g.....g.....",
            "....g.....g.....",
            "...rrr...rrr....",
            "..rwrrr.rwrrr...",
            "..rrrrr.rrrrr...",
            "..rrrrr.rrrrr...",
            "...rrr...rrr....",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "LEMON", "label": "Citron", "maps": "LED",
        "art": [
            "................",
            "................",
            "................",
            "............yy..",
            "....yyyyyyyyy...",
            "..yyyyyyyyyyyy..",
            ".yywwyyyyyyyyyy.",
            ".yywyyyyyyyyyyy.",
            ".yyyyyyyyyyyyyy.",
            "..yyyyyyyyyYYy..",
            "...yyyyyyyyYY...",
            "..yy............",
            "................",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "ORANGE", "label": "Orange", "maps": "CHIP",
        "art": [
            "................",
            "......ggg.......",
            ".....gg.........",
            "....oooooooo....",
            "...oooooooooo...",
            "..owwoooooooohh.".replace("h", "o"),
            "..owoooooooooo..",
            "..oooooooooooo..",
            "..oooooooooooo..",
            "..oooooooooYYo..",
            "...ooooooooYY...",
            "....oooooooo....",
            "................",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "PLUM", "label": "Prune", "maps": "FLOPPY",
        "art": [
            "................",
            "........gg......",
            ".......gg.......",
            "....vvvvvvvv....",
            "...vvvvvvvvvv...",
            "..vwwvvvvvvvvv..",
            "..vwvvvvvvvvvv..",
            "..vvvvvvvvvvvv..",
            "..vvvvvvvvvvvv..",
            "..vvvvvvvvvVVv..",
            "...vvvvvvvvVV...",
            "....vvvvvvvv....",
            "................",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "MELON", "label": "Pastèque", "maps": "GAMEPAD",
        "art": [
            "................",
            "................",
            "................",
            "....rrrrrrrr....",
            "...rrrrrrrrrr...",
            "..rrkrrrrkrrrr..",
            "..rrrrrrrrrrrr..",
            ".rrrrkrrrrrkrrr.",
            ".rrrrrrrrrrrrrr.",
            ".wwwwwwwwwwwwww.",
            ".gggggggggggggg.",
            "..gGGGGGGGGGGg..",
            "....gGGGGGGg....",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "BELL", "label": "Cloche", "maps": "CRT",
        "art": [
            "................",
            "......ss........",
            "......ss........",
            ".....yyyy.......",
            "....yywyyy......",
            "....ywyyyy......",
            "...yywyyyyy.....",
            "...yyyyyyyy.....",
            "..yyyyyyyyyy....",
            "..yyyyyyyyyy....",
            ".yyyyyyyyyyyy...",
            ".YYYYYYYYYYYY...",
            "......ww........",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "BAR", "label": "BAR", "maps": "D20",
        "art": [
            "................",
            "................",
            "................",
            "................",
            ".kkkkkkkkkkkkkk.",
            ".kwwwwwwwwwwwwk.",
            ".kwkkw.kk.wkkwk.",
            ".kwkwkwkwkwkwkk.".replace("kk.", "kk."),
            ".kwkkwwkkkwkkwk.",
            ".kwkwkwkwkwkwkk.",
            ".kwkkw.kwk.wkwk.",
            ".kwwwwwwwwwwwwk.",
            ".kkkkkkkkkkkkkk.",
            "................",
            "................",
            "................",
        ],
    },
    {
        "id": "SEVEN", "label": "Sept", "maps": "INVADER",
        "art": [
            "................",
            "................",
            "..wwwwwwwwwwww..",
            "..wrrrrrrrrrrw..",
            "..wrrrrrrrrrrw..",
            "..wwwwwwwrrrww..",
            "........wrrrw...",
            ".......wrrrw....",
            "......wrrrw.....",
            ".....wrrrw......",
            "....wrrrw.......",
            "....wrrrw.......",
            "....wrrrw.......",
            "....wwwww.......",
            "................",
            "................",
        ],
    },
]

# Petits pictogrammes d'interface, 12x12 — pas des symboles de rouleau.
ICONS = {
    "COIN": {
        "label": "Jeton", "size": 12,
        "art": [
            "....kkkk....",
            "..kkyyyykk..",
            ".kyyyyyyyyk.",
            ".kyyYYYYyyk.",
            "kyyYkkkkYyyk",
            "kyyYkyykYyyk",
            "kyyYkyykYyyk",
            "kyyYkkkkYyyk",
            ".kyyYYYYyyk.",
            ".kyyyyyyyyk.",
            "..kkyyyykk..",
            "....kkkk....",
        ],
    },
    "SPEAKER": {
        "label": "Son", "size": 12,
        "art": [
            "........c...",
            "......kc.c..",
            "...kkkk.c.c.",
            "..kkssk.c.c.",
            ".kksssk.c.c.",
            "ksssssk.c.c.",
            "ksssssk.c.c.",
            ".kksssk.c.c.",
            "..kkssk.c.c.",
            "...kkkk.c.c.",
            "......kc.c..",
            "........c...",
        ],
    },
    "BALL": {
        "label": "Pommeau du levier", "size": 12,
        "art": [
            "....kkkk....",
            "..kkrrrrkk..",
            ".krwwrrrrrk.",
            ".krwrrrrrrk.",
            "krrrrrrrrrrk",
            "krrrrrrrrrrk",
            "krrrrrrrrrrk",
            "krrrrrrrrrrk",
            ".krrrrrrrrk.",
            ".krrrrrrrrk.",
            "..kkrrrrkk..",
            "....kkkk....",
        ],
    },
    "LEVER": {
        "label": "Levier", "size": 12,
        "art": [
            "....rrrr....",
            "...rrrrrr...",
            "...rrwwrr...",
            "....rrrr....",
            ".....ss.....",
            ".....ss.....",
            ".....ss.....",
            ".....ss.....",
            "....SSSS....",
            "...kSSSSk...",
            "..kkSSSSkk..",
            "..kkkkkkkk..",
        ],
    },
}
